# Generated by Django 6.1.1 on 2026-10-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_epi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
    ]
