# Generated by Django 6.1.1 on 2026-10-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_epi', '0002_remove_colaborador_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='id',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
